apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-uid
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Postgres
    uid: postgres-uid
    type: postgres
    access: proxy
    url: db:5432
    database: maintenance
    user: maintenance
    secureJsonData:
      password: maintenance_secret
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    editable: false